# run-in-four-nines
name: 4-9-job-level-group-lease

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: example-group}
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v2

      - name: Random step
        run: sleep 10
        
      - name: Another Random step
        run: sleep 10
