# run-in-four-nines
name: 4-9-plan-level-long-group-lease-name

on:
  workflow_dispatch:

concurrency:
  group: "namenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename"
  cancel-in-progress: true

jobs:
  job-1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Random step
        run: sleep 10
        
      - name: Another Random step
        run: sleep 10
