name: reused-with-embedded-conc

concurrency: reusable-embedded-conc

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    concurrency: job-reusable
    environment: test
    steps:
    - name: First step
      run: echo "Hello, world!"  
    - name: Second step
      run: sleep 70
