name: reusableB

on:
  workflow_call:

concurrency: reusable-top-level

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v4
    - run: echo "Hello, world!"  
    - run: sleep 30
